/** Test ids of the Forest building blocks; a page's sections get theirs from the screen. */
export const forestTestIds = {
  metaBar: 'forest-meta-bar',
  hero: 'forest-hero',
  name: 'forest-name',
  headline: 'forest-headline',
  subtitle: 'forest-subtitle',
  photo: 'forest-photo',
  lead: 'forest-lead',
  contact: 'forest-contact',
  impactCard: 'forest-impact-card',
  loopStep: 'forest-loop-step',
  loopFootnote: 'forest-loop-footnote',
  job: 'forest-job',
  earlier: 'forest-earlier',
  app: 'forest-app',
  skill: 'forest-skill',
  book: 'forest-book',
  footer: 'forest-footer',
} as const;
