export const retroTestIds = {
  dock: 'retro-dock',
  chat: 'retro-chat',
  chatLog: 'retro-chat-log',
  chatLine: 'retro-chat-line',
  chatInput: 'retro-chat-input',
  console: 'retro-console',
  consoleScreen: 'retro-console-screen',
  consoleErrors: 'retro-console-errors',
  consoleWarnings: 'retro-console-warnings',
  minimise: 'retro-minimise',
  decoration: 'retro-decoration',
  highlight: 'retro-highlight',
  highlightBox: 'retro-highlight-box',
} as const;
